// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5PB5qCyELTTB2Fu8TWkbXw
// Component: sYtCQE2xB7EwA
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import ActionButton from "../../ActionButton"; // plasmic-import: ThTj1ia1xzyMF/component
import Spacer from "../../Spacer"; // plasmic-import: kNGmokXiskPehV/component
import Avatar from "../../Avatar"; // plasmic-import: znvNxN-p8NmP4I/component
import Button from "../../Button"; // plasmic-import: AN_TmxifACLjxq/component
import Tweet from "../../Tweet"; // plasmic-import: xdy9x6J9RGV7j/component
import SideSection from "../../SideSection"; // plasmic-import: Y_COCBceTE-ZK1/component
import Trend from "../../Trend"; // plasmic-import: JKT-Ml_ZZCz0qd/component
import Suggestion from "../../Suggestion"; // plasmic-import: lVvWKYP_zUrgxj/component

import { useScreenVariants as useScreenVariantsx9ArTzcY8BnJDn } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: x9arTzcY8bnJDn/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_copy_of_twitter_primary_copy.module.css"; // plasmic-import: 5PB5qCyELTTB2Fu8TWkbXw/projectcss
import sty from "./PlasmicFeed.module.css"; // plasmic-import: sYtCQE2xB7EwA/css

import MagicIcon from "./icons/PlasmicIcon__Magic"; // plasmic-import: j5U3TjL1kXsdvq/icon
import TwitterIcon from "./icons/PlasmicIcon__Twitter"; // plasmic-import: DtnIz9PinSoHSa/icon
import HomeActiveIcon from "./icons/PlasmicIcon__HomeActive"; // plasmic-import: 2BpcZIF5IteUnp/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: 8MOjGNV_1qeSqW/icon
import NotificationsIcon from "./icons/PlasmicIcon__Notifications"; // plasmic-import: PPK87QlPRHfRqZ/icon
import MessagesIcon from "./icons/PlasmicIcon__Messages"; // plasmic-import: l2pdskzpfhCCII/icon
import BookmarksIcon from "./icons/PlasmicIcon__Bookmarks"; // plasmic-import: Vp7Nfx0vuFPKyJ/icon
import ListsIcon from "./icons/PlasmicIcon__Lists"; // plasmic-import: D3t9W9GL9AoVuF/icon
import ProfileIcon from "./icons/PlasmicIcon__Profile"; // plasmic-import: gmUJmu_DPUWeeP/icon
import MoreIcon from "./icons/PlasmicIcon__More"; // plasmic-import: WFPSHm2dgSIJJb/icon
import PictureIcon from "./icons/PlasmicIcon__Picture"; // plasmic-import: U5f2JRhopY-PM7/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: sFy4MHVjmJmERd/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: jUjrai2Jm5u1rb/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: wYGGecPv2CTFQP/icon
import Icon7Icon from "./icons/PlasmicIcon__Icon7"; // plasmic-import: T_8E2r33_tTcYR/icon
import SearchIcon from "./icons/PlasmicIcon__Search"; // plasmic-import: Z9Z2LpTcL87TkY/icon

export type PlasmicFeed__VariantMembers = {};

export type PlasmicFeed__VariantsArgs = {};
type VariantPropType = keyof PlasmicFeed__VariantsArgs;
export const PlasmicFeed__VariantProps = new Array<VariantPropType>();

export type PlasmicFeed__ArgsType = {};
type ArgPropType = keyof PlasmicFeed__ArgsType;
export const PlasmicFeed__ArgProps = new Array<ArgPropType>();

export type PlasmicFeed__OverridesType = {
  root?: p.Flex<"div">;
  avatar?: p.Flex<typeof Avatar>;
  newTweetInput?: p.Flex<"textarea">;
  tweetButton?: p.Flex<typeof Button>;
  tweetList?: p.Flex<"div">;
  searchInput?: p.Flex<"input">;
};

export interface DefaultFeedProps {}

function PlasmicFeed__RenderFunc(props: {
  variants: PlasmicFeed__VariantsArgs;
  args: PlasmicFeed__ArgsType;
  overrides: PlasmicFeed__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsx9ArTzcY8BnJDn()
  });

  return (
    <React.Fragment>
      {}

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox___2Jlao)}>
            <div className={classNames(projectcss.all, sty.freeBox__jx0Kz)}>
              {(
                hasVariant(globalVariants, "screen", "desktop") ? false : true
              ) ? (
                <div className={classNames(projectcss.all, sty.freeBox__i61A)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__a6Czp)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__v8G9I)}
                      displayHeight={"30px" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"30px" as const}
                      src={{
                        src: "/plasmic/copy_of_twitter_primary_copy/images/image2.png",
                        fullWidth: 225,
                        fullHeight: 223,
                        aspectRatio: undefined
                      }}
                    />
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nCpKk
                    )}
                  >
                    {"Home"}
                  </div>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__rciNj
                    )}
                    options={["medium", "primary"]}
                    slot={"25"}
                  >
                    <MagicIcon
                      className={classNames(projectcss.all, sty.svg___1ILem)}
                      role={"img"}
                    />
                  </ActionButton>
                </div>
              ) : null}
              {(
                hasVariant(globalVariants, "screen", "desktop") ? true : false
              ) ? (
                <div className={classNames(projectcss.all, sty.freeBox__z1DHs)}>
                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__a8QSv
                    )}
                    options={["primary", "large"]}
                    slot={"25"}
                  >
                    <TwitterIcon
                      className={classNames(projectcss.all, sty.svg___1Uqtr)}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__k3XTl
                    )}
                    options={["primary", "large"]}
                    slot={"25"}
                  >
                    <HomeActiveIcon
                      className={classNames(projectcss.all, sty.svg__xYrZw)}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__lyd9F
                    )}
                    options={["large"]}
                    slot={"25"}
                  >
                    <Icon2Icon
                      className={classNames(projectcss.all, sty.svg__jvuYx)}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton___0BTgn
                    )}
                    options={["large"]}
                    slot={"25"}
                  >
                    <NotificationsIcon
                      className={classNames(projectcss.all, sty.svg__fXwah)}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__xd9Tl
                    )}
                    options={["large"]}
                    slot={"25"}
                  >
                    <MessagesIcon
                      className={classNames(projectcss.all, sty.svg__oCGdx)}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__ydRoI
                    )}
                    options={["large"]}
                    slot={"25"}
                  >
                    <BookmarksIcon
                      className={classNames(projectcss.all, sty.svg__ljO26)}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__djfmr
                    )}
                    options={["large"]}
                    slot={"25"}
                  >
                    <ListsIcon
                      className={classNames(projectcss.all, sty.svg__gnEsM)}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton___4XbEt
                    )}
                    options={["large"]}
                    slot={"25"}
                  >
                    <ProfileIcon
                      className={classNames(projectcss.all, sty.svg__yoKaR)}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton___2IzJa
                    )}
                    options={["large"]}
                    slot={"25"}
                  >
                    <MoreIcon
                      className={classNames(projectcss.all, sty.svg__pHuM)}
                      role={"img"}
                    />
                  </ActionButton>
                </div>
              ) : null}
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__zvMes)}>
              {(
                hasVariant(globalVariants, "screen", "desktop") ? true : false
              ) ? (
                <div className={classNames(projectcss.all, sty.freeBox__f3LPn)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__tUkPa)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yuoCz
                      )}
                    >
                      {"Home"}
                    </div>

                    <Spacer
                      className={classNames(
                        "__wab_instance",
                        sty.spacer___0TUlv
                      )}
                    />

                    <ActionButton
                      className={classNames(
                        "__wab_instance",
                        sty.actionButton__ptJmX
                      )}
                      options={["medium", "primary"]}
                      slot={"25"}
                    >
                      <MagicIcon
                        className={classNames(projectcss.all, sty.svg__yYz97)}
                        role={"img"}
                      />
                    </ActionButton>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox___0UHWb)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__aH3Kw)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___24K0U
                        )}
                      >
                        <Avatar
                          data-plasmic-name={"avatar"}
                          data-plasmic-override={overrides.avatar}
                          className={classNames("__wab_instance", sty.avatar)}
                        />
                      </p.Stack>
                    </p.Stack>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__m5ZpB)}
                    >
                      <textarea
                        data-plasmic-name={"newTweetInput"}
                        data-plasmic-override={overrides.newTweetInput}
                        className={classNames(
                          projectcss.all,
                          projectcss.textarea,
                          sty.newTweetInput
                        )}
                        placeholder={"What's happening?" as const}
                        rows={1 as const}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___2XpIs
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__tPmuS
                          )}
                        >
                          <ActionButton
                            className={classNames(
                              "__wab_instance",
                              sty.actionButton___2OqUd
                            )}
                            options={["medium", "primary"]}
                            slot={"25"}
                          >
                            <PictureIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__v2Gwc
                              )}
                              role={"img"}
                            />
                          </ActionButton>

                          <ActionButton
                            className={classNames(
                              "__wab_instance",
                              sty.actionButton__xrDoC
                            )}
                            options={["medium", "primary"]}
                            slot={"25"}
                          >
                            <Icon3Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg___0PCLi
                              )}
                              role={"img"}
                            />
                          </ActionButton>

                          <ActionButton
                            className={classNames(
                              "__wab_instance",
                              sty.actionButton__kZu8A
                            )}
                            options={["medium", "primary"]}
                            slot={"25"}
                          >
                            <Icon4Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__wQy2F
                              )}
                              role={"img"}
                            />
                          </ActionButton>

                          <ActionButton
                            className={classNames(
                              "__wab_instance",
                              sty.actionButton__avOmv
                            )}
                            options={["medium", "primary"]}
                            slot={"25"}
                          >
                            <Icon5Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__xg7Jv
                              )}
                              role={"img"}
                            />
                          </ActionButton>

                          <ActionButton
                            className={classNames(
                              "__wab_instance",
                              sty.actionButton__hk0Qw
                            )}
                            options={["medium", "primary"]}
                            slot={"25"}
                          >
                            <Icon7Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__ehnI
                              )}
                              role={"img"}
                            />
                          </ActionButton>
                        </p.Stack>

                        <Spacer
                          className={classNames(
                            "__wab_instance",
                            sty.spacer___0OfB1
                          )}
                        />

                        <Button
                          data-plasmic-name={"tweetButton"}
                          data-plasmic-override={overrides.tweetButton}
                          className={classNames(
                            "__wab_instance",
                            sty.tweetButton
                          )}
                          options={["primary"]}
                        >
                          {"Tweet"}
                        </Button>
                      </div>
                    </div>
                  </div>
                </div>
              ) : null}

              <div
                data-plasmic-name={"tweetList"}
                data-plasmic-override={overrides.tweetList}
                className={classNames(projectcss.all, sty.tweetList)}
              >
                <Tweet
                  className={classNames("__wab_instance", sty.tweet__wliPo)}
                />

                <Tweet
                  className={classNames("__wab_instance", sty.tweet__gdq5W)}
                  name={"Cassidy Williams"}
                  photo={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__hjVwh)}
                      displayHeight={"49px" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"49px" as const}
                      src={{
                        src: "/plasmic/copy_of_twitter_primary_copy/images/image4.png",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  username={"@cassidoo"}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__mo2L5)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uGqzI
                      )}
                    >
                      {"A new issue is coming your way, check your inbox!!"}
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__x3G1G)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__zHfVc)}
                        displayHeight={"140px" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"140px" as const}
                        src={{
                          src: "/plasmic/copy_of_twitter_primary_copy/images/image5.png",
                          fullWidth: 240,
                          fullHeight: 240,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__sgHMu
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___3OugB
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>{""}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"rendezvous with cassidoo"}
                            </span>
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__jwfKl
                          )}
                        >
                          {"probably the best newsletter you'll ever read"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ww7Tz
                          )}
                        >
                          {"cassidoo.co"}
                        </div>
                      </div>
                    </p.Stack>
                  </p.Stack>
                </Tweet>

                <Tweet
                  className={classNames("__wab_instance", sty.tweet__msbBv)}
                  name={"Max Stoiber"}
                  photo={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__uQFhw)}
                      displayHeight={"49px" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"49px" as const}
                      src={{
                        src: "/plasmic/copy_of_twitter_primary_copy/images/image7.png",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  username={"@mxstbr"}
                >
                  {
                    "Tell me you're a React developer without telling me you're a React developer."
                  }
                </Tweet>

                <Tweet
                  className={classNames("__wab_instance", sty.tweet__kfAje)}
                />

                <Tweet
                  className={classNames("__wab_instance", sty.tweet__mgrZe)}
                  name={"Cassidy Williams"}
                  photo={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__fzQk1)}
                      displayHeight={"49px" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"49px" as const}
                      src={{
                        src: "/plasmic/copy_of_twitter_primary_copy/images/image4.png",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  username={"@cassidoo"}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__abIzJ)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fGye4
                      )}
                    >
                      {"A new issue is coming your way, check your inbox!!"}
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__sKwpD)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__iaKA)}
                        displayHeight={"140px" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"140px" as const}
                        src={{
                          src: "/plasmic/copy_of_twitter_primary_copy/images/image5.png",
                          fullWidth: 240,
                          fullHeight: 240,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__dweiT
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wn4Mn
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>{""}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"rendezvous with cassidoo"}
                            </span>
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__y8St4
                          )}
                        >
                          {"probably the best newsletter you'll ever read"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___9VJgN
                          )}
                        >
                          {"cassidoo.co"}
                        </div>
                      </div>
                    </p.Stack>
                  </p.Stack>
                </Tweet>

                <Tweet
                  className={classNames("__wab_instance", sty.tweet___8Popk)}
                  name={"Max Stoiber"}
                  photo={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__xvpbO)}
                      displayHeight={"49px" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"49px" as const}
                      src={{
                        src: "/plasmic/copy_of_twitter_primary_copy/images/image7.png",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  username={"@mxstbr"}
                >
                  {
                    "Tell me you're a React developer without telling me you're a React developer."
                  }
                </Tweet>
              </div>
            </div>

            {(
              hasVariant(globalVariants, "screen", "desktop") ? true : false
            ) ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__yrqgx)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__beeHf)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__rSw1)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__wmc0U)}
                    >
                      <SearchIcon
                        className={classNames(projectcss.all, sty.svg__bcKvq)}
                        role={"img"}
                      />
                    </div>

                    <input
                      data-plasmic-name={"searchInput"}
                      data-plasmic-override={overrides.searchInput}
                      className={classNames(
                        projectcss.all,
                        projectcss.input,
                        sty.searchInput
                      )}
                      placeholder={"Search Twitter" as const}
                      size={1 as const}
                      type={"text" as const}
                    />
                  </div>
                </div>

                <SideSection
                  className={classNames(
                    "__wab_instance",
                    sty.sideSection__bci8X
                  )}
                  slot={
                    <React.Fragment>
                      <Trend
                        className={classNames(
                          "__wab_instance",
                          sty.trend__vdYhy
                        )}
                        slot={"Entertainment"}
                      >
                        {
                          "Adele shares photo supporting Beyoncé's Black is King"
                        }
                      </Trend>

                      <Trend
                        className={classNames(
                          "__wab_instance",
                          sty.trend__fcBr
                        )}
                        slot={"COVID-19"}
                      >
                        {
                          "Thousands march in Berlin to protest COVID-19 restrictions"
                        }
                      </Trend>

                      <Trend
                        className={classNames(
                          "__wab_instance",
                          sty.trend___8NpcU
                        )}
                        slot={"World nenws"}
                      >
                        {
                          "Russia banned from using its name, flag and anthem at the next two Olympic Games"
                        }
                      </Trend>
                    </React.Fragment>
                  }
                />

                <SideSection
                  className={classNames(
                    "__wab_instance",
                    sty.sideSection__tfPmo
                  )}
                  slot={
                    <React.Fragment>
                      <Suggestion
                        className={classNames(
                          "__wab_instance",
                          sty.suggestion__ebO
                        )}
                        slot={"Mark Dalgleish      "}
                        slot2={"@markdalgleish"}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img___65CD)}
                          displayHeight={"49px" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"none" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"49px" as const}
                          src={{
                            src: "/plasmic/copy_of_twitter_primary_copy/images/image6.png",
                            fullWidth: 400,
                            fullHeight: 400,
                            aspectRatio: undefined
                          }}
                        />
                      </Suggestion>

                      <Suggestion
                        className={classNames(
                          "__wab_instance",
                          sty.suggestion__zi4S
                        )}
                        slot={"Guillermo Rauch  "}
                        slot2={"@rauchg"}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__s2GYn)}
                          displayHeight={"49px" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"none" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"49px" as const}
                          src={{
                            src: "/plasmic/copy_of_twitter_primary_copy/images/image8.png",
                            fullWidth: 400,
                            fullHeight: 400,
                            aspectRatio: undefined
                          }}
                        />
                      </Suggestion>
                    </React.Fragment>
                  }
                >
                  {"Who to follow"}
                </SideSection>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__ztIn7)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__wuoX4)}
                  >
                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__yKv8C
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"Terms"}
                    </p.PlasmicLink>

                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__pbxAx
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"Privacy policy"}
                    </p.PlasmicLink>

                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__enRmv
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"Cookies"}
                    </p.PlasmicLink>

                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__o0T1J
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"Ads info"}
                    </p.PlasmicLink>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__yT2L)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ptZl2
                      )}
                    >
                      {"© 2021 Twitter, Inc."}
                    </div>
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            ) : null}
            {(
              hasVariant(globalVariants, "screen", "desktop") ? false : true
            ) ? (
              <div className={classNames(projectcss.all, sty.freeBox__gODw)}>
                <ActionButton
                  className={classNames(
                    "__wab_instance",
                    sty.actionButton__nHvcv
                  )}
                  options={["medium", "primary"]}
                  slot={"25"}
                >
                  <HomeActiveIcon
                    className={classNames(projectcss.all, sty.svg__ra3J7)}
                    role={"img"}
                  />
                </ActionButton>

                <ActionButton
                  className={classNames(
                    "__wab_instance",
                    sty.actionButton__faq1R
                  )}
                  options={["medium"]}
                  slot={"25"}
                >
                  <SearchIcon
                    className={classNames(projectcss.all, sty.svg__y7CsM)}
                    role={"img"}
                  />
                </ActionButton>

                <ActionButton
                  className={classNames(
                    "__wab_instance",
                    sty.actionButton__pKcYi
                  )}
                  options={["medium"]}
                  slot={"25"}
                >
                  <NotificationsIcon
                    className={classNames(projectcss.all, sty.svg__iiyvH)}
                    role={"img"}
                  />
                </ActionButton>

                <ActionButton
                  className={classNames(
                    "__wab_instance",
                    sty.actionButton__tFa3
                  )}
                  options={["medium"]}
                  slot={"25"}
                >
                  <MessagesIcon
                    className={classNames(projectcss.all, sty.svg__yv3Uu)}
                    role={"img"}
                  />
                </ActionButton>
              </div>
            ) : null}
            {false ? (
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__wOQxU)}
                displayHeight={"731px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"none" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"411px" as const}
                src={{
                  src: "/plasmic/copy_of_twitter_primary_copy/images/image.png",
                  fullWidth: 1079,
                  fullHeight: 1919,
                  aspectRatio: undefined
                }}
              />
            ) : null}
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "avatar",
    "newTweetInput",
    "tweetButton",
    "tweetList",
    "searchInput"
  ],
  avatar: ["avatar"],
  newTweetInput: ["newTweetInput"],
  tweetButton: ["tweetButton"],
  tweetList: ["tweetList"],
  searchInput: ["searchInput"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  avatar: typeof Avatar;
  newTweetInput: "textarea";
  tweetButton: typeof Button;
  tweetList: "div";
  searchInput: "input";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFeed__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFeed__VariantsArgs;
    args?: PlasmicFeed__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicFeed__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicFeed__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFeed__ArgProps,
      internalVariantPropNames: PlasmicFeed__VariantProps
    });

    return PlasmicFeed__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFeed";
  } else {
    func.displayName = `PlasmicFeed.${nodeName}`;
  }
  return func;
}

export const PlasmicFeed = Object.assign(
  // Top-level PlasmicFeed renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    avatar: makeNodeComponent("avatar"),
    newTweetInput: makeNodeComponent("newTweetInput"),
    tweetButton: makeNodeComponent("tweetButton"),
    tweetList: makeNodeComponent("tweetList"),
    searchInput: makeNodeComponent("searchInput"),

    // Metadata about props expected for PlasmicFeed
    internalVariantProps: PlasmicFeed__VariantProps,
    internalArgProps: PlasmicFeed__ArgProps
  }
);

export default PlasmicFeed;
/* prettier-ignore-end */
